services:
  briar-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: briar-bot:latest
    container_name: briar-bot-prod
    restart: unless-stopped
    
    # Environment
    environment:
      - NODE_ENV=production
      - TZ=${TIMEZONE:-UTC}
    
    # Load environment variables from .env file
    env_file:
      - .env
    
    # Persistent storage
    volumes:
      - ./cache:/app/cache:rw
      - ./logs:/app/logs:rw
      - /etc/localtime:/etc/localtime:ro
    
    # Resource limits for home server
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.8'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Health monitoring
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('OK'); process.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 120s
    
    # Security
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Efficient logging for production
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "2"
        compress: "true"
    
    # Metadata
    labels:
      - "com.briarbot.service=discord-bot"
      - "com.briarbot.environment=production"
      - "com.briarbot.version=2.0"